apiVersion: v1
data:
  REDIS_NODES: redis-0.redis,redis-1.redis,redis-2.redis
  redis.conf: |
    daemonize no
    supervised no
    loglevel notice
    logfile ""
    databases 16
    always-show-logo yes
    save ""
    stop-writes-on-bgsave-error yes
    rdbcompression yes
    rdbchecksum yes
    rdb-del-sync-files no
    dir "/data"
    replica-serve-stale-data yes
    replica-read-only yes
    repl-diskless-sync no
    repl-diskless-sync-delay 5
    repl-diskless-load disabled
    appendonly no
    repl-disable-tcp-nodelay no
    replica-priority 100
    acllog-max-len 128
kind: ConfigMap
metadata:
  name: redis-config-map
  namespace: redis

