apiVersion: v1
data:
  redis_init.sh: |
    #!/bin/bash
    cp /tmp/redis/redis.conf /etc/redis/redis.conf
    echo "requirepass ${REDIS_PASSWORD}" >> /etc/redis/redis.conf
    echo "masterauth ${REDIS_PASSWORD}" >> /etc/redis/redis.conf
    echo "replica-announce-ip ${HOSTNAME}.redis-ha" >> /etc/redis/redis.conf
    echo "replica-announce-port 6379 " >> /etc/redis/redis.conf

    echo "finding master..."
    if [ "$(timeout 5 redis-cli -h sentinel -p 5000 -a ${REDIS_PASSWORD} ping)" != "PONG" ]; then
      echo "sentinel not found, defaulting to redis-ha-0"
      if [ ${HOSTNAME} == "redis-ha-0" ]; then
        echo "this is redis-ha-0, not updating config..."
      else
        echo "updating redis.conf..."
        echo "repl-ping-replica-period 3" >> /etc/redis/redis.conf
        echo "slave-read-only no" >> /etc/redis/redis.conf
        echo "slaveof redis-ha-0.redis-ha 6379" >> /etc/redis/redis.conf
      fi
    else
      echo "sentinel found, finding master"
      MASTER="$(redis-cli -h sentinel -p 5000 -a ${REDIS_PASSWORD} sentinel get-master-addr-by-name mymaster | grep -E '(^redis-*)|([0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3})')"
      if [ "${HOSTNAME}.redis-ha" == ${MASTER} ]; then
        echo "this is master, not updating config..."
      else
        echo "master found : ${MASTER}, updating redis.conf"
        echo "slave-read-only no" >> /etc/redis/redis.conf
        echo "slaveof ${MASTER} 6379" >> /etc/redis/redis.conf
        echo "repl-ping-replica-period 3" >> /etc/redis/redis.conf
      fi
    fi
  sentinel_init.sh: "#!/bin/bash\nfor i in ${REDIS_NODES//,/ }\ndo\n    echo \"finding
    master at $i\"\n    MASTER=$(redis-cli --no-auth-warning --raw -h $i -a ${REDIS_PASSWORD}
    info replication | awk '{print $1}' | grep master_host: | cut -d \":\" -f2)\n
    \   \n    if [ \"${MASTER}\" == \"\" ]; then\n        echo \"no master found\"\n
    \       MASTER=\n    else\n        echo \"found ${MASTER}\"\n        break\n    fi\n
    \   \ndone\necho \"sentinel monitor mymaster ${MASTER} 6379 2\" >> /tmp/master\n\necho
    \"port 5000\nsentinel resolve-hostnames yes\nsentinel announce-hostnames yes\n$(cat
    /tmp/master)\n\nsentinel down-after-milliseconds mymaster 1000\nsentinel failover-timeout
    mymaster 10000\nsentinel parallel-syncs mymaster 1\n\nsentinel sentinel-pass ${REDIS_PASSWORD}\nsentinel
    auth-pass mymaster ${REDIS_PASSWORD}\nrequirepass ${REDIS_PASSWORD}\nsentinel
    announce-ip ${HOSTNAME}.sentinel\nsentinel announce-port 5000\n\" > /etc/redis/sentinel.conf\ncat
    /etc/redis/sentinel.conf\n"
kind: ConfigMap
metadata:
  name: redis-scripts-config-map
  namespace: redis

